# eksctl specification for AWS k8s cluster
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: microservices1-cluster
  region: eu-west-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 1

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["audit", "authenticator", "controllerManager"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"
