version: "3.7"

services:
  reverseproxy:
    build:
      context: ./udacity-c3-deployment/docker
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - restapi-user
      - restapi-feed
    ports:
      - 8080:8080
  users-feed-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
  restapi-user:
    build:
      context: ./udacity-c3-restapi-user
      dockerfile: Dockerfile
    volumes:
      - "./udacity-c3-restapi-user:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 8082:8080
    env_file:
      - ./.env.dev
    environment:
      - NODE_ENV=development
    depends_on:
      - users-feed-db
  restapi-feed:
    build:
      context: ./udacity-c3-restapi-feed
      dockerfile: Dockerfile
    volumes:
      - "./udacity-c3-restapi-feed:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 8081:8080
    env_file:
      - ./.env.dev
    environment:
      - NODE_ENV=development
    depends_on:
      - users-feed-db
  client:
    build:
      context: ./udacity-c3-frontend
      dockerfile: Dockerfile
    volumes:
      - "./udacity-c3-frontend:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 8100:80
    environment:
      - NODE_ENV=development
    depends_on:
      - users-feed-db
