# Run containers locally with prod details, uses env_file
version: "3.7"

services:
  reverseproxy:
    build:
      context: ./udacity-c3-deployment/docker
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - restapi-users
      - restapi-feed
    ports:
      - 8080:8080
  restapi-users:
    build:
      context: ./udacity-c3-restapi-user
      dockerfile: Dockerfile.prod
    volumes:
      - "./udacity-c3-restapi-user:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 8082:8080
    env_file:
      - ./.env.prod
    environment:
      - NODE_ENV=production
  restapi-feed:
    build:
      context: ./udacity-c3-restapi-feed
      dockerfile: Dockerfile.prod
    volumes:
      - "./udacity-c3-restapi-feed:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 8081:8080
    env_file:
      - ./.env.prod
    environment:
      - NODE_ENV=production
  client:
    build:
      context: ./udacity-c3-frontend
      dockerfile: Dockerfile
    volumes:
      - "./udacity-c3-frontend:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 8100:80
    environment:
      - NODE_ENV=production
