apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: restapi-feed
  name: restapi-feed
spec:
  replicas: 3
  template:
    metadata:
      labels:
        service: restapi-feed
    spec:
      containers:
        - image: scheele/udacity-restapi-feed
          name: restapi-feed
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: S3_BUCKET
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_PROFILE
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_REGION
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: JWT_SECRET
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: DB_HOST
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: DB_PASS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: DB_USER
          volumeMounts:
            - name: aws-secret
              mountPath: "/root/.aws/"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
