apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: restapi-feed
  name: restapi-feed
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: restapi-feed
    spec:
      containers:
        - image: ./../udacity-c3-restapi-feed/Dockerfile
          name: restapi-feed
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
            - name: S3_BUCKET
              valueFrom:
                configKeyMapRef:
                  name: env-config
                  key: S3_BUCKET

            - name: AWS_REGION
              valueFrom:
                configKeyMapRef:
                  name: env-config
                  key: AWS_REGION

            - name: AWS_PROFILE
              valueFrom:
                configKeyMapRef:
                  name: env-config
                  key: AWS_PROFILE

            - name: JWT_SECRET
              valueFrom:
                configKeyMapRef:
                  name: env-config
                  key: JWT_SECRET

            - name: DB_HOST
              valueFrom:
                configKeyMapRef:
                  name: env-config
                  key: DB_HOST

            - name: DB_USER
              valueFrom:
                configKeyMapRef:
                  name: env-config
                  key: DB_USER

            - name: DB_PASS
              valueFrom:
                configKeyMapRef:
                  name: env-config
                  key: DB_PASS

            - name: DB_NAME
              valueFrom:
                configKeyMapRef:
                  name: env-config
                  key: DB_NAME

            - name: DB_PORT
              valueFrom:
                configKeyMapRef:
                  name: env-config
                  key: DB_PORT

            - name: DB_PROTOCOL
              valueFrom:
                configKeyMapRef:
                  name: env-config
                  key: DB_PROTOCOL
            volumeMounts:
            - name: aws-secret
              mountPath: "/root/.aws/"
              readOnly: true
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret
